<?php
define("Tadmin","admin");
define("Tfeebacks","feedbacks");
define("Tstudy_branches","study_branches");
define("Tstudy_city","study_city");
define("Tstudy_college","study_college");
define("Tstudy_college_courses","study_college_courses");
define("Tstudy_comments","study_comments");
define("Tstudy_country","study_country");
define("Tstudy_courses","study_courses");
define("Tstudy_error","study_error");
define("Tstudy_likes","study_likes");
define("Tstudy_material","study_material");
define("Tstudy_semester","study_semester");
define("Tstudy_year","study_year");
define("Tstudy_state","study_state");
define("Tstudy_subject","study_subject");
define("Tstudy_users","study_users");
define("Tstudy_team_members","study_team_members");
define("Tstudy_team_type","study_team_type");
?>